# Generated by Django 5.0.7 on 2024-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
