# Generated by Django 5.0.7 on 2024-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animecharacter_highlight_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecharacter',
            name='diary',
            field=models.TextField(default='diary1', max_length=500),
            preserve_default=False,
        ),
    ]
